apiVersion: apps/v1
kind: Deployment
metadata:
  name: selection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selection-service
  template:
    metadata:
      labels:
        app: selection-service
    spec:
      containers:
        - name: selection-service
          image: crpi-pik0sdrslhyp68pn.cn-hangzhou.personal.cr.aliyuncs.com/qwoyu/selection-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 18030
---
apiVersion: v1
kind: Service
metadata:
  name: selection-service
spec:
  type: ClusterIP
  selector:
    app: selection-service
  ports:
    - port: 18030
      targetPort: 18030
